name: My first Workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repo
          uses: actions/checkout@v4

        - name: My first message
          run: echo "Welcome to github actions"

        - name: List the files 
          run: ls

        - name: Read file
          run: cat README.md