name: My first Workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repo
          uses: actions/checkout@v4

        - name: Multiple command (single step - executing multiple commands)
          run: | 
               echo "Welcome to github actions"
               ls
               cat README.md