name: Generating ASCCI Artwork

on: 
  push

jobs:
  build_job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
      
    - name: Installing dependencies
      run: sudo apt-get install cowsay
    
    - name: Execting cowsay
      run: cowsay -f dragon "I AM DRAGON" >> dragon.txt

  test_job:
    needs: build_job
    runs-on: ubuntu-latest
    steps:
    - name: Read the file
      run: grep -i "dragon" dragon.txt
      
    - name: List the files
      run: ls -ltra

  deploy_job: 
    needs: test_job
    runs-on: ubuntu-latest
    steps:
    - name: Read the file
      run: cat dragon.txt
      
    - name: Deploying cowsay
      run: echo "Deploying"