name: Generating ASCCI Artwork

on: 
  push

jobs:
  build_job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
      
    - name: List the files
      run: ls -ltra
    
    - name: Execting cowsay
      run: cowsay -f dragon "I AM DRAGON" >> dragon.txt

  test_job:
    runs-on: ubuntu-latest
    steps:
    - name: Read the file
      uses: grep -i "dragon" dragon.txt
      
    - name: List the files
      run: ls -ltra

  deploy_job:
    runs-on: ubuntu-latest
    steps:
    - name: Read the file
      uses: cat dragon.txt
      
    - name: Deploying cowsay
      run: echo "Deploying"