name: Exporing Variable and Secrets

on:
  push

env:
    CONTAINER_RESGISTRY: Docker.io
    IMAGE_NAME: github-actions-nginx

jobs:
   build:
     runs-on: ubuntu_latest
     steps:
     - name: Docker Build
       run: echo docker build -t ${{ env.CONTAINER_RESGISTRY }}/${{ vars.DOCKER_USERNAME}}/$IMAGE_NAME:latest
    
     - name: Docker Login
       run: echo docker login --username=${{ vars.DOCKER_USERNAME }} --password=${{ secrets.PASSWORD}}

